import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { Book } from '../shared/autogenerated-api';
import { environment } from 'src/environments/environment';
import { Observable } from 'rxjs';
@Component({
  selector: 'app-fetch-books',
  templateUrl: './fetch-books.component.html',
  styleUrls: ['./fetch-books.component.scss']
})
export class FetchBooksComponent implements OnInit {

  constructor(private http: HttpClient) { }

  public displayedColumns: string[] = ['BookTitle', 'Author', 'Price', 'Category'];

  dataSource: Book[] = [];

  ngOnInit(): void {
    this.load();
  }

  load() {
    const BASE_URL: string = environment.apiBaseUrl;
    this.http.get<any[]>(BASE_URL + 'rest/books/getAllBooks').subscribe(x => {
      this.dataSource = x;
    });
  }
}
